eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
mybatis:
    configuration:
        cacheEnabled: false
        mapUnderscoreToCamelCase: true
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.easymall.pojo
server:
    port: 10001
spring:
    application:
        name: product-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        maxActive: 50
        maxIdle: 10
        minIdle: 5
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://116.205.130.21:3306/easydb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
        username: loomt
    redis:
        host: 116.205.130.21
        port: 6379
        database: 0
        jedis:
            pool:
                max-active: 50
                max-wait: 1ms
                max-idle: 8
                min-idle: 0