eureka:
    client:
        serviceUrl:
            defaultZone:
                - http://localhost:8761/eureka/
                - http://localhost:8762/eureka/
mybatis:
    configuration:
        cacheEnabled: false
        mapUnderscoreToCamelCase: true
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: cn.edu.scnu.entity
server:
    port: 8092
spring:
    application:
        name: order-service
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/microtest?useSSL=false
        username: loomt
