server:
  port: 10003
  contentPath: /
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 50
    maxIdle: 10
    minIdle: 5
    password: 123456
    username: loomt
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://116.205.130.21:3306/easydb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
  redis:
#    jedis:
#      pool:
#        max-active: 50
#        max-wait: 1s
#        max-idle: 8
#        min-idle: 0
    shard:
      max-total: 200
      max-idle: 10
      min-idle: 2
      nodes:
        - 116.205.130.21:6379
        - 116.205.130.21:6380
        - 116.205.130.21:6381
mybatis:
  typeAliasesPackage: com.easymall.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    cacheEnabled: false