server:
  port: 8762 #服务端口
spring:
  application:
    name: eureka-server #eureka的服务名称
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    hostname: localhost