server:
  port: 9005
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
        - id: pic
          uri: lb://pic-service
          predicates:
            - Path=/pic-service/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - id: seckill
          uri: lb://seckill-service
          predicates:
            - Path=/seckill-service/**
      discovery:
        locator:
          enabled: true
      default-filters: # 全局过滤器
        - StripPrefix=1
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone:
      - http://localhost:8761/eureka
      - http://localhost:8762/eureka