server:
  port: 11000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/loomt/emconfig
      label: master
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone:
        - http://localhost:8761/eureka
        - http://localhost:8762/eureka
