spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        maxActive: 50
        maxIdle: 10
        minIdle: 5
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://116.205.130.21:3306/easydb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
        username: loomt