server:
  port: 9005
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api-a
          uri: lb://service01
          predicates:
            - Path=/api-a/**
        - id: api-b
          uri: lb://service02
          predicates:
            - Path=/api-b/**
        - id: orders
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: users
          uri: lb://user-service
          predicates:
            - Path=/users/**
      discovery:
        locator:
          enabled: true
      default-filters: # 全局过滤器
        - StripPrefix=1
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone:
      - http://localhost:8761/eureka
      - http://localhost:8762/eureka