version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis01:
    container_name: redis01
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis01.conf --port 6379
    volumes:
      - ./redis01.conf:/usr/local/etc/redis/redis01.conf
    ports:
      - 6379:6379

  redis02:
    container_name: redis02
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis02.conf --port 6380
    volumes:
      - ./redis02.conf:/usr/local/etc/redis/redis02.conf
    ports:
      - 6380:6380

  redis03:
    container_name: redis03
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis03.conf --port 6381
    volumes:
      - ./redis03.conf:/usr/local/etc/redis/redis03.conf
    ports:
      - 6381:6381

  redis6382:
    container_name: redis6382
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis6382.conf --port 6382
    volumes:
      - ./redis6382.conf:/usr/local/etc/redis/redis6382.conf
    ports:
      - 6382:6382
  redis6383:
    container_name: redis6383
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis6383.conf --port 6383 --replicaof 192.168.0.242 6382
    volumes:
      - ./redis6383.conf:/usr/local/etc/redis/redis6383.conf
    ports:
      - 6383:6383
  redis6384:
    container_name: redis6384
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis6384.conf --port 6384 --replicaof 192.168.0.242 6382
    volumes:
      - ./redis6384.conf:/usr/local/etc/redis/redis6384.conf
    ports:
      - 6384:6384
