version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379