eureka:
    client:
        serviceUrl:
            defaultZone:
                - http://localhost:8761/eureka/
                - http://localhost:8762/eureka/
server:
    port: 9004
spring:
    application:
        name: ribbon-service